import { JobPosting, Candidate, Campaign, Template, Channel } from './types';

export const mockJobs: JobPosting[] = [
  {
    id: 'JOB-001',
    title: 'Senior Frontend Developer',
    shortId: 'FE-2025-01',
    location: 'San Francisco, CA',
    type: 'Full-time',
    status: 'Live',
    applications: 47,
    avgMatch: 87,
    views: 1240,
    postedDate: '2025-07-20',
    expiryDate: '2025-08-20',
    hiringStage: 'Interviewing',
    owner: 'Sarah Chen',
    department: 'Engineering',
    tags: ['React', 'TypeScript', 'Frontend', 'Senior'],
    description: 'We are looking for a senior frontend developer to join our growing engineering team...',
    requirements: ['5+ years React experience', 'TypeScript proficiency', 'Leadership experience'],
    benefits: ['Health Insurance', 'Stock Options', 'Remote Work', 'Learning Budget'],
    salaryRange: { min: 140000, max: 180000, currency: 'USD' },
    remote: true
  },
  {
    id: 'JOB-002',
    title: 'Product Manager',
    shortId: 'PM-2025-02',
    location: 'Remote',
    type: 'Full-time',
    status: 'Live',
    applications: 32,
    avgMatch: 74,
    views: 890,
    postedDate: '2025-07-18',
    expiryDate: '2025-08-18',
    hiringStage: 'Screening',
    owner: 'Michael Rodriguez',
    department: 'Product',
    tags: ['Product Management', 'Strategy', 'Remote', 'Senior'],
    description: 'Join our product team to drive product strategy and execution...',
    requirements: ['3+ years PM experience', 'Technical background', 'Data-driven approach'],
    benefits: ['Health Insurance', 'Stock Options', 'Flexible Hours', 'Remote Work'],
    salaryRange: { min: 120000, max: 160000, currency: 'USD' },
    remote: true
  },
  {
    id: 'JOB-003',
    title: 'UX Designer',
    shortId: 'UX-2025-03',
    location: 'New York, NY',
    type: 'Full-time',
    status: 'Draft',
    applications: 0,
    avgMatch: 0,
    views: 0,
    postedDate: '2025-07-25',
    hiringStage: 'Not Started',
    owner: 'Emily Davis',
    department: 'Design',
    tags: ['UX Design', 'Figma', 'Research', 'Mid-level'],
    description: 'We are seeking a talented UX designer to create exceptional user experiences...',
    requirements: ['3+ years UX experience', 'Figma proficiency', 'Portfolio required'],
    benefits: ['Health Insurance', 'Learning Budget', 'Gym Membership'],
    salaryRange: { min: 90000, max: 120000, currency: 'USD' },
    remote: false
  },
  {
    id: 'JOB-004',
    title: 'Backend Engineer',
    shortId: 'BE-2025-04',
    location: 'Austin, TX',
    type: 'Full-time',
    status: 'Paused',
    applications: 23,
    avgMatch: 82,
    views: 650,
    postedDate: '2025-07-10',
    hiringStage: 'On Hold',
    owner: 'Alex Johnson',
    department: 'Engineering',
    tags: ['Node.js', 'Python', 'Backend', 'Senior'],
    description: 'Looking for a backend engineer to build scalable systems...',
    requirements: ['4+ years backend experience', 'Node.js or Python', 'Database design'],
    benefits: ['Health Insurance', 'Stock Options', '401k Matching'],
    salaryRange: { min: 130000, max: 170000, currency: 'USD' },
    remote: true
  },
  {
    id: 'JOB-005',
    title: 'Data Scientist',
    shortId: 'DS-2025-05',
    location: 'Seattle, WA',
    type: 'Full-time',
    status: 'Live',
    applications: 18,
    avgMatch: 91,
    views: 420,
    postedDate: '2025-07-22',
    expiryDate: '2025-08-22',
    hiringStage: 'Sourcing',
    owner: 'Lisa Wang',
    department: 'Data',
    tags: ['Machine Learning', 'Python', 'Statistics', 'Senior'],
    description: 'Join our data science team to build ML models and drive insights...',
    requirements: ['PhD or Masters in related field', 'Python/R proficiency', 'ML experience'],
    benefits: ['Health Insurance', 'Stock Options', 'Conference Budget'],
    salaryRange: { min: 150000, max: 200000, currency: 'USD' },
    remote: true
  },
  {
    id: 'JOB-006',
    title: 'DevOps Engineer',
    shortId: 'DO-2025-06',
    location: 'Denver, CO',
    type: 'Contract',
    status: 'Expired',
    applications: 12,
    avgMatch: 68,
    views: 350,
    postedDate: '2025-06-15',
    expiryDate: '2025-07-15',
    hiringStage: 'Closed',
    owner: 'David Kim',
    department: 'Infrastructure',
    tags: ['DevOps', 'Docker', 'Kubernetes', 'Contract'],
    description: 'Contract position for DevOps engineer to improve our infrastructure...',
    requirements: ['3+ years DevOps experience', 'Docker/Kubernetes', 'AWS/GCP'],
    benefits: ['Competitive Rate', 'Flexible Schedule'],
    salaryRange: { min: 80, max: 120, currency: 'USD' },
    remote: true
  }
];

export const mockCandidates: Candidate[] = [
  {
    id: 'CAND-001',
    name: 'John Smith',
    email: 'john.smith@email.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    jobId: 'JOB-001',
    jobTitle: 'Senior Frontend Developer',
    stage: 'Interview',
    matchScore: 92,
    appliedDate: '2025-07-22',
    source: 'LinkedIn'
  },
  {
    id: 'CAND-002',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop',
    jobId: 'JOB-001',
    jobTitle: 'Senior Frontend Developer',
    stage: 'Phone',
    matchScore: 85,
    appliedDate: '2025-07-21',
    source: 'Company Site'
  },
  {
    id: 'CAND-003',
    name: 'Mike Chen',
    email: 'mike.chen@email.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    jobId: 'JOB-002',
    jobTitle: 'Product Manager',
    stage: 'Screened',
    matchScore: 78,
    appliedDate: '2025-07-20',
    source: 'Indeed',
    flagged: true,
    flagReason: 'Missing required experience'
  },
  {
    id: 'CAND-004',
    name: 'Emma Wilson',
    email: 'emma.w@email.com',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    jobId: 'JOB-001',
    jobTitle: 'Senior Frontend Developer',
    stage: 'Applied',
    matchScore: 95,
    appliedDate: '2025-07-24',
    source: 'Referral'
  },
  {
    id: 'CAND-005',
    name: 'David Lee',
    email: 'david.lee@email.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
    jobId: 'JOB-005',
    jobTitle: 'Data Scientist',
    stage: 'Offer',
    matchScore: 88,
    appliedDate: '2025-07-19',
    source: 'LinkedIn'
  },
  {
    id: 'CAND-006',
    name: 'Lisa Zhang',
    email: 'lisa.zhang@email.com',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop',
    jobId: 'JOB-002',
    jobTitle: 'Product Manager',
    stage: 'Rejected',
    matchScore: 65,
    appliedDate: '2025-07-17',
    source: 'Glassdoor'
  }
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'CAM-001',
    name: 'Frontend Developer Campaign Q3',
    jobId: 'JOB-001',
    jobTitle: 'Senior Frontend Developer',
    budget: 5000,
    spend: 3200,
    impressions: 45000,
    clicks: 890,
    applications: 47,
    cpc: 3.6,
    status: 'Active',
    channels: ['LinkedIn', 'Indeed', 'Stack Overflow'],
    startDate: '2025-07-20',
    endDate: '2025-08-20'
  },
  {
    id: 'CAM-002',
    name: 'Product Manager Recruitment',
    jobId: 'JOB-002',
    jobTitle: 'Product Manager',
    budget: 3000,
    spend: 1800,
    impressions: 28000,
    clicks: 560,
    applications: 32,
    cpc: 3.2,
    status: 'Active',
    channels: ['LinkedIn', 'AngelList'],
    startDate: '2025-07-18',
    endDate: '2025-08-18'
  },
  {
    id: 'CAM-003',
    name: 'Data Science Talent Hunt',
    jobId: 'JOB-005',
    jobTitle: 'Data Scientist',
    budget: 4000,
    spend: 2100,
    impressions: 15000,
    clicks: 320,
    applications: 18,
    cpc: 6.6,
    status: 'Active',
    channels: ['Kaggle Jobs', 'AI Jobs Board'],
    startDate: '2025-07-22',
    endDate: '2025-08-22'
  }
];


export const mockTemplates: Template[] = [
  {
    id: 'TPL-001',
    name: 'Senior Engineer Job Description',
    description: 'Standard template for senior engineering positions',
    type: 'Job Description',
    content: '## About the Role\n\nWe are looking for a senior engineer...',
    category: 'Engineering',
    usageCount: 23,
    lastUsed: '2025-07-20',
    isPublic: true
  },
  {
    id: 'TPL-002',
    name: 'LinkedIn Campaign Copy',
    description: 'Proven LinkedIn ad copy for technical roles',
    type: 'Campaign',
    content: "Join our innovative team! We're hiring {{job_title}}...",
    category: 'Marketing',
    usageCount: 15,
    lastUsed: '2025-07-18',
    isPublic: false
  },
  {
    id: 'TPL-003',
    name: 'Interview Invitation Email',
    description: 'Professional email template for interview invitations',
    type: 'Email',
    content: 'Hi {{candidate_name}}, Thank you for your application...',
    category: 'Communication',
    usageCount: 87,
    lastUsed: '2025-07-25',
    isPublic: true
  }
];

export const mockChannels: Channel[] = [
  {
    id: 'CH-001',
    name: 'LinkedIn Jobs',
    type: 'Job Board',
    connected: true,
    lastPosted: '2025-07-25',
    impressions: 15000,
    applyRate: 5.2,
    cost: 299,
    logo: '/logos/linkedin.png'
  },
  {
    id: 'CH-002',
    name: 'Indeed',
    type: 'Job Board',
    connected: true,
    lastPosted: '2025-07-24',
    impressions: 12000,
    applyRate: 3.8,
    cost: 199,
    logo: '/logos/indeed.png'
  },
  {
    id: 'CH-003',
    name: 'Company Website',
    type: 'Company',
    connected: true,
    lastPosted: '2025-07-25',
    impressions: 5000,
    applyRate: 8.5,
    cost: 0,
    logo: '/logos/company.png'
  },
  {
    id: 'CH-004',
    name: 'Stack Overflow Jobs',
    type: 'Job Board',
    connected: false,
    impressions: 0,
    applyRate: 0,
    cost: 0,
    logo: '/logos/stackoverflow.png'
  }
];